config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

	get 'index' => 'welcome#index'
  get 'param', to: 'welcome#about_params'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@homeland = 'USA'
  	@countries = ['Switzerland', 'Russia', 'Germany']
  	@countries_pics = ['Russia.jpeg', 'Canada.jpeg']
  	
  end

  def about_params
  	if params[:color] == nil
  		@color = "orange"
  	else
  	@color = params[:color]
  end

  	@size = params[:shoe_size]


  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travel</title>
    <%= csrf_meta_tags %>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href='http://fonts.googleapis.com/css?family=Marck+Script' rel='stylesheet' type='text/css'>

    
  </head>

  <body>
  <div class='container'>
    <%= yield %>
   </div>

  </body>
</html>

app/views/welcome/about_params.html.erb
<style>
  body {
    background: <%= @color %>;
  }
</style>

<h1>Welcome#about_params</h1>

<p>Find me in app/views/welcome/params.html.erb</p>
<h3>My favorite color is <%= @color %></h3>

<% if @size.to_i >= 12 %>
  <h3>My shoe size is <%= @size %>. I have HUGE feet!</h3>
<% else %>
  <h3>My shoe size is <%= @size %></h3>
<% end %>

<%= link_to "Blue", param_path(color: "blue"), class: "btn btn-primary" %>
<%= link_to "Red", param_path(color: "red"), class: "btn btn-danger" %>


<%= link_to "Index", index_path %>

<br>
<br>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= @homeland %>
<ul>
	<% @countries.each do | country |%>
		<li><%= country %></li>
	<% end %>	
</ul>



<%= image_tag 'Japan.jpg', alt: 'Japan',
						   id: 'Japan', 
						   class: 'img-responsive',
						   height: 300,
						   width: 400 %>


<%= image_tag 'Canada.jpg', alt: 'Japan',
						   id: 'Canada', 
						   class: 'img-responsive',
						   height: 300,
						   width: 400 %>
						   <br>

<%= link_to "Params", param_path %>


<br>
<br>